### ISSUE TITLE
[Python] Safe LRO imports for both gRPC and non-gRPC clients

### ISSUE THREAD

**Issue by bjwatson** [googleapis/packman#112]
### What

The import of `operations_pb2.py` from [`googleapi-common-protos`](https://pypi.python.org/pypi/googleapis-common-protos) should work with or without gRPC. If the gRPC dependency is present, then it should include the long-running operations (LRO) service methods. This is currently working in `googleapi-common-protos` 1.3.4, but it was done manually. We want `packman` to handle this automatically for future releases.
### Why

Google App Engine Standard for Python does not currently support gRPC, and needs to use the HTTP/JSON mode of https://github.com/GoogleCloudPlatform/gcloud-python/. There may be other use cases that would also prefer or require HTTP/JSON. [`googleapi-common-protos`](https://pypi.python.org/pypi/googleapis-common-protos) now has a soft dependency on gRPC to support the LRO service methods, and we need to make sure that `operations_pb2.py` can be imported with or without gRPC.
### How

See what I manually did with `generated/python/googleapis-common-protos/google/longrunning/operations_pb2.py` in https://github.com/googleapis/api-client-staging/pull/1 for version 1.3.4 of [`googleapi-common-protos`](https://pypi.python.org/pypi/googleapis-common-protos).

**Comment by bjwatson** [comment]
FYI @nathanielmanistaatgoogle. I can close this issue if you end up solving this problem in grpc-python.

**Comment by nathanielmanistaatgoogle** [comment]
I've opened [grpc issue 8056](https://github.com/grpc/grpc/issues/8056) for the discussion.

**Comment by bjwatson** [comment]
Thanks @nathanielmanistaatgoogle.

**Comment by bjwatson** [comment]
This is fixed by gRPC 1.0.2
