### ISSUE TITLE
Add a flag to allow java packages to be java source packages rather than proto

### ISSUE THREAD

**Issue by tbetbetbe** [googleapis/packman#20]
- add a flag `experimental_java_src_pkgs` that's recognized during java package builds that causes the java package to be a source package rather than a proto package

FYI: @garrettjonesgoogle

**Comment by garrettjonesgoogle** [comment]
FYI: @michaelbausor

**Comment by garrettjonesgoogle** [comment]
Why not compiled classes too?

**Comment by tbetbetbe** [comment]
That works as well.  The simplest approach is to
- [ ] add the necessary steps to the build.gradle template
- [ ] use gradle to run the steps

So
- having an java SDK in installed is a pre-req of this flag  
- anything that can be done with a gradle task can be done

**Comment by tbetbetbe** [comment]
FYI: t's actually not necessary for packman to run gradle.
Currently it does not do this, it just creates the build.gradle file.  This is in keeping with how it operates in other languages, where it prepares the format for other tools to run.
