### ISSUE TITLE
The gax README should explain the entry points for the API

### ISSUE THREAD

**Issue by jmuk** [googleapis/packman#32]
After finished the docgen for Ruby, I've noticed that the generated doc page contains tons of classes and hard to find which class to look at.

See http://www.rubydoc.info/gems/gax-google-logging-v2/0.6.2 for example, it's hard to notice that Google > Logging > V2 > LoggingServiceV2Api (and ConfigServiceV2Api and MetricsServiceV2Api) are the classes people should look at.

Possibly, the toplevel README.md should list these classes with links, so that the users can quickly navigate to the primary documents.

I think the same thing is applied to Python...  Thoughts?  cc: @tbetbetbe

**Comment by jmuk** [comment]
Turns out that Python does not suffer from this issue, as far as I look at http://pythonhosted.org/gax-google-pubsub-v1/, but this will be necessary for Ruby packages.

**Comment by tbetbetbe** [comment]
LGTM, please sync before submitting.  If possible, it'd be nice to see a demo url (you can show taht offline if you like)
