### ISSUE TITLE
build-alt.gradle.mustache is not rendered when "experimental_alt_java" flag is set.

### ISSUE THREAD

**Issue by shinfan** [googleapis/packman#54]
Repro steps:

1. Checkout staging-eap repo
2. Run pubsub GRPC client code gen pipeline:
     python execute_pipeline.py \
        --config "../googleapis/gapic/api/artman_pubsub.yaml:common|java,\
        ../googleapis/gapic/lang/common.yaml:default|java" \
        JavaGrpcClientPipeline
3. I confirmed that the pipeline added --experimental_alt_java when calling pipeline
4. The generated gradle.build file is not rendered from build-alt.gradle.mustache

**Comment by garrettjonesgoogle** [comment]
This is working currently
